#!/usr/bin/env python3
"""Generate src/font.h: a 1bpp 8x16 bitmap atlas for ASCII 32..126.

The Game Switcher UI links against core SDL2 only -- SDL2_ttf's headers are
stripped from the device by cleanup_filesystem.sh -- so glyphs are baked into
the binary at authoring time.  Run this only when the font needs regenerating;
the generated header is committed.

    python3 gameswitcher/tools/genfont.py > gameswitcher/src/font.h
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FONT_SIZE = 13
CELL_W, CELL_H = 8, 16
FIRST, LAST = 32, 126


def render(ch, font):
    # Mode "1" keeps rendering monochrome: no antialiasing to threshold later.
    img = Image.new("1", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    # Anchor on the baseline so caps and descenders both stay inside the cell
    # instead of leaving the font's internal leading as dead rows at the top.
    draw.text((0, 12), ch, font=font, fill=1, anchor="ls")
    return img


def main():
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    rows = []
    for code in range(FIRST, LAST + 1):
        img = render(chr(code), font)
        px = img.load()
        glyph = []
        for y in range(CELL_H):
            bits = 0
            for x in range(CELL_W):
                if px[x, y]:
                    bits |= 1 << (7 - x)
            glyph.append(bits)
        rows.append((code, glyph))

    out = sys.stdout
    out.write("/* Generated by gameswitcher/tools/genfont.py -- do not edit by hand. */\n")
    out.write("#ifndef GS_FONT_H_INCLUDED\n#define GS_FONT_H_INCLUDED\n\n")
    out.write("#define GS_FONT_W %d\n#define GS_FONT_H %d\n" % (CELL_W, CELL_H))
    out.write("#define GS_FONT_FIRST %d\n#define GS_FONT_LAST %d\n\n" % (FIRST, LAST))
    out.write("/* One byte per scanline, MSB = leftmost pixel. */\n")
    out.write("static const unsigned char gs_font[%d][%d] = {\n" % (LAST - FIRST + 1, CELL_H))
    for code, glyph in rows:
        label = chr(code) if code != 92 else "backslash"
        body = ", ".join("0x%02x" % b for b in glyph)
        out.write("    { %s }, /* '%s' */\n" % (body, label))
    out.write("};\n\n#endif /* GS_FONT_H_INCLUDED */\n")


if __name__ == "__main__":
    main()
